import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file: string) => readFileSync(path.join(root, file), "utf8");

const cardPath = "src/components/write-canvas/CanvasNodeCard.tsx";
const menuPath = "src/components/write-canvas/CanvasNodeAddMenu.tsx";
const editorPath = "src/components/write-canvas/CanvasDocumentEditor.tsx";

assert.equal(existsSync(path.join(root, cardPath)), true, "Unified canvas node card must exist");
assert.equal(existsSync(path.join(root, menuPath)), true, "Contextual node plus menu must exist");
assert.equal(existsSync(path.join(root, editorPath)), true, "Canvas document editor must exist");

const page = read("src/pages/MagicWritingCanvas.tsx");
const card = read(cardPath);
const menu = read(menuPath);
const editor = read(editorPath);
const inspector = read("src/components/write-canvas/CanvasInspector.tsx");

assert.match(card, /node\.role|roleLabel/, "Node shell must render semantic roles");
assert.match(card, /node\.status|statusLabel/, "Node shell must render persisted status");
assert.match(card, /CanvasNodeAddMenu/, "Every business card must expose its contextual plus menu");
assert.doesNotMatch(card, /role="button"/, "Node shell must not wrap its menu buttons in another interactive control");
assert.match(menu, /新建子节点/);
assert.match(menu, /AI 拆解/);
assert.match(menu, /创建作品/);
assert.match(page, /atomflow-canvas-node-action/, "Canvas page must handle node-local actions");
assert.match(page, /event\.key === 'Tab'|event\.key === "Tab"/, "Tab must create a child branch outside editors");
assert.match(page, /event\.key === 'Enter'|event\.key === "Enter"/, "Enter must create a sibling branch outside editors");
assert.match(page, /\[role="button"\]/, "Global branch shortcuts must ignore interactive role targets");
assert.match(page, /if \(!linked\)[\s\S]{0,300}method: 'DELETE'/, "Failed structure links must roll back their orphan child node");
assert.match(page, /let receivedFinal = false/, "Quick AI must distinguish a terminal final event from a truncated stream");
assert.match(page, /if \(!receivedFinal\)[\s\S]{0,120}throw new Error/, "Quick AI must reject streams that close before the final event");
assert.match(page, /quickActionAbortControllerRef/, "Quick AI must keep an AbortController for explicit cancellation");
assert.match(page, /signal:\s*abortController\.signal/, "Quick AI requests must be wired to the cancellation signal");
assert.match(page, /取消生成/, "Quick AI must expose an explicit cancel action while running");
assert.match(page, /setActivePanel\(null\)[\s\S]{0,220}setAiDecomposeNodeId\(node\.id\)/, "Opening Quick AI must close other canvas overlays");
assert.match(page, /pendingNodeGeometryRef/, "User geometry edits must be tracked before the debounce expires");
assert.match(page, /getChangedNodeGeometry/, "Geometry persistence must derive dirty nodes from the store diff");
assert.doesNotMatch(page.match(/const stopGeometryListener[\s\S]*?\}, \{ source: 'user', scope: 'document' \}\);/)?.[0] || '', /getCurrentPageShapes/, "Geometry events must not mark every canvas node dirty");
assert.match(page, /mergePendingNodeGeometry/, "Server detail reloads must preserve optimistic local geometry");
assert.match(page, /flushPendingNodeGeometry/, "Pending node geometry must be flushable before project changes");
assert.match(page, /persistPendingNodeGeometryDraft/, "Page unload must preserve changed geometry without one request per node");
assert.match(page, /sessionStorage[\s\S]{0,300}CANVAS_TAB_ID/, "each browser tab must keep an independent geometry draft namespace");
assert.match(page, /NODE_GEOMETRY_DRAFT_KEY_PREFIX[^\n]*projectId[^\n]*canvasTabIdRef/, "geometry drafts from separate tabs must not overwrite one another");
assert.match(page, /expectedUpdatedAt:\s*geometry\.baseUpdatedAt/, "geometry persistence must use the node version captured before the drag");
assert.match(page, /NODE_VERSION_CONFLICT/, "stale geometry writes must reconcile to the canonical server node");
assert.match(page, /nodeGeometryFlushPromisesRef/, "geometry writes for one node must be serialized");
assert.match(page, /savedNode\.updatedAt[\s\S]{0,500}baseUpdatedAt/, "a successful geometry write must rebase later local movement onto the returned node version");
assert.match(page, /pending\.baseUpdatedAt !== node\.updatedAt[\s\S]{0,180}nodeGeometryFlushPromisesRef\.current\.has\(node\.id\)/, "a stale detail response must not discard geometry while that node is still flushing");
assert.doesNotMatch(page.match(/const handlePageHide[\s\S]{0,220}/)?.[0] || '', /flushPendingNodeGeometry/, "Page unload must not fan out geometry requests");
assert.match(page, /isLocked:\s*edge\.relation !== 'context'/, "Canonical structure and generated arrows must be non-editable");
assert.match(page, /ignoreShapeLock:\s*true/, "Server synchronization must still update and remove locked canonical arrows");
assert.match(page, /edge\.relation !== 'context'[\s\S]{0,600}createBoundEdge/, "Changed non-context bindings must be restored from server state");
assert.match(page, /activePanelRef\.current !== null/, "Branch shortcuts must be disabled while a canvas panel is open");
assert.match(page, /input, textarea, select, button, a\[href\]/, "Branch shortcuts must preserve interactive focus navigation");
assert.match(page, /sourceNodeId:\s*source\.id/, "Creating a document from a node must preserve source lineage");
assert.match(page, /QUICK_ACTION_RECONCILE_MAX_ATTEMPTS/, "Quick AI terminal reconciliation must be bounded");
assert.match(page, /projects\/\$\{projectId\}\/runs/, "Quick AI cancellation must reconcile against durable project runs");
assert.match(page, /observedRunId/, "Quick AI reconciliation must prefer the run id observed from SSE");
assert.match(page, /await reconcileQuickActionRun/, "Quick AI failure and cancellation must wait for durable terminal state before refreshing");
assert.match(page, /\/api\/write\/canvas\/edges\/replace/, "Context arrow rewiring must use the atomic replace endpoint");
assert.match(page, /edgeId,\s*sourceNodeId:\s*source\.id,\s*targetNodeId:\s*target\.id/, "Atomic rewiring must identify the old edge and both new endpoints");
assert.match(page, /target\?\.kind === 'agent'[\s\S]{0,220}target\?\.role === 'task'[\s\S]{0,120}target\?\.contentType === 'agent_group'/, "Context arrows must accept canonical Agent-group task nodes");
const canonicalArrowReconcile = page.match(/const reconcileCanonicalArrowChanges[\s\S]*?\n  \}, \[[^\n]+\]\);/)?.[0] || '';
assert.doesNotMatch(canonicalArrowReconcile, /method:\s*'DELETE'/, "Context rewiring must not use a create-then-delete sequence");
assert.doesNotMatch(canonicalArrowReconcile, /fetch\('\/api\/write\/canvas\/edges',\s*\{[\s\S]{0,100}method:\s*'POST'/, "Context rewiring must not create a second edge before removing the first");
const branchKeyHandlerStart = page.lastIndexOf('const keyHandler = (event: KeyboardEvent) => {');
const branchKeyHandlerEnd = page.indexOf("window.addEventListener('atomflow-canvas-node-action'", branchKeyHandlerStart);
const branchKeyHandler = page.slice(branchKeyHandlerStart, branchKeyHandlerEnd);
assert.doesNotMatch(branchKeyHandler, /event\.defaultPrevented\s*\|\|/, "tldraw preventDefault must not suppress the Tab branch shortcut");
assert.match(branchKeyHandler, /interactiveSelector/, "Tab branching must still yield to focused interactive controls");
assert.doesNotMatch(branchKeyHandler, /\[tabindex\]/, "the focusable tldraw canvas itself must not be mistaken for an overlay control");
assert.match(page, /quickActionRunSequenceRef/, "late Quick AI events must be isolated from newer runs");
assert.match(page, /pendingNodeGeometryRef\.current\.delete\(nodeId\)[\s\S]{0,180}persistPendingNodeGeometryDraft/, "successful node deletion must clear its geometry draft from memory and local storage");
assert.match(page, /CANVAS_AI_ACTIVE[\s\S]{0,300}loadProjectDetail/, "a protected node deletion must restore the canonical canvas and explain the conflict");
assert.match(page, /observedAgentRunId/, "single-Agent streaming must remember the durable run id");
assert.match(page, /meta\?\.runId[\s\S]{0,500}setAgentInput/, "a truncated Agent stream must check persisted messages before restoring the prompt");
assert.match(page, /selectedIds\.length !== 1[\s\S]{0,220}setSelectedNodeId\(null\)/, "Multi-selection and arrow selection must clear stale business selection");
assert.match(inspector, /node\.role === 'document'|node\.role === "document"/, "Inspector must route document nodes to the document editor");
assert.match(editor, /useEditor\(/, "Document editing must use Tiptap");
assert.match(editor, /sections/, "Document editor must keep ordered outline sections and bodies together");
assert.match(editor, /CANVAS_DOCUMENT_SCENARIOS/, "Document editor must expose the first content-creation scenarios");
assert.match(editor, /downloadCanvasDocument/, "Completed work must be exportable without leaving the canvas");

console.log("PASS: unified canvas node and document UI contracts");
