import { randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { Environment, Paddle } from "@paddle/paddle-node-sdk";
import bcrypt from "bcryptjs";
import dotenv from "dotenv";
import pg from "pg";
import {
  priceMatchesSandboxPlan,
  renderSandboxBillingEnv,
  SANDBOX_CLIENT_TOKEN_NAME,
  SANDBOX_NOTIFICATION_DESCRIPTION,
  SANDBOX_PLAN_SPECS,
  SANDBOX_PRODUCT_KEY,
  SANDBOX_PRODUCT_NAME,
  SANDBOX_WEBHOOK_EVENTS,
  validateLocalPostgresUrl,
  validateSandboxWebhookUrl,
} from "../src/server/billing/sandboxSetup.js";

const GENERATED_MARKER = "# Generated by scripts/setup-paddle-sandbox.ts.";
const OUTPUT_PATH = path.resolve(process.cwd(), ".env.billing.sandbox");
const TEST_ACCOUNT_OUTPUT_PATH = path.resolve(process.cwd(), ".env.billing.test-account");
const verifyOnly = process.argv.includes("--verify-only");
const localAccountOnly = process.argv.includes("--local-account-only");
const unknownArguments = process.argv.slice(2).filter(argument => !["--verify-only", "--local-account-only"].includes(argument));

const required = (name: string) => {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
};

const asRecord = (value: unknown): Record<string, unknown> => (
  value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}
);

const collect = async <T>(collection: AsyncIterable<T>) => {
  const rows: T[] = [];
  for await (const row of collection) rows.push(row);
  return rows;
};

const oneOrNone = <T>(rows: T[], label: string) => {
  if (rows.length > 1) throw new Error(`Multiple ${label} resources match AtomFlow identity; resolve duplicates in Paddle first`);
  return rows[0] || null;
};

type SandboxNotificationSetting = {
  id: string;
  description: string;
  type: string;
  destination: string;
  active: boolean;
  includeSensitiveFields: boolean;
  trafficSource: string;
  subscribedEvents: Array<{ name: string }>;
  endpointSecretKey: string;
};

type SandboxNotificationCreate = {
  description: string;
  type: "url";
  destination: string;
  subscribedEvents: Array<(typeof SANDBOX_WEBHOOK_EVENTS)[number]>;
  includeSensitiveFields: false;
  trafficSource: "all";
};

type SandboxNotificationUpdate = {
  description?: string;
  destination?: string;
  active?: boolean;
  subscribedEvents?: Array<(typeof SANDBOX_WEBHOOK_EVENTS)[number]>;
  includeSensitiveFields?: boolean;
  trafficSource?: "all";
};

type SandboxNotificationResource<T extends SandboxNotificationSetting> = {
  create: (body: SandboxNotificationCreate) => Promise<T>;
  update: (id: string, body: SandboxNotificationUpdate) => Promise<T>;
};

const notificationHasExpectedConfiguration = (
  notification: SandboxNotificationSetting,
  webhookUrl: string,
) => {
  const currentEvents = notification.subscribedEvents.map(event => event.name).sort();
  const expectedEvents = [...SANDBOX_WEBHOOK_EVENTS].sort();
  return notification.active
    && notification.destination === webhookUrl
    && notification.description === SANDBOX_NOTIFICATION_DESCRIPTION
    && notification.includeSensitiveFields === false
    && notification.trafficSource === "all"
    && JSON.stringify(currentEvents) === JSON.stringify(expectedEvents);
};

export const reconcileSandboxNotificationSetting = async <T extends SandboxNotificationSetting>({
  notificationSettings,
  webhookUrl,
  verifyOnly,
  resource,
}: {
  notificationSettings: T[];
  webhookUrl: string;
  verifyOnly: boolean;
  resource: SandboxNotificationResource<T>;
}) => {
  const managed = notificationSettings
    .filter(item => item.type === "url" && item.description === SANDBOX_NOTIFICATION_DESCRIPTION)
    .sort((left, right) => left.id.localeCompare(right.id));
  const canonical = managed.find(item => item.active && item.destination === webhookUrl)
    || managed.find(item => item.destination === webhookUrl)
    || managed.find(item => item.active)
    || managed[0]
    || null;

  if (!canonical) {
    if (verifyOnly) throw new Error("AtomFlow Sandbox webhook destination is missing");
    return resource.create({
      description: SANDBOX_NOTIFICATION_DESCRIPTION,
      type: "url",
      destination: webhookUrl,
      subscribedEvents: [...SANDBOX_WEBHOOK_EVENTS],
      includeSensitiveFields: false,
      trafficSource: "all",
    });
  }

  const activeDuplicates = managed.filter(item => item.id !== canonical.id && item.active);
  if (verifyOnly && activeDuplicates.length > 0) {
    throw new Error(
      `Multiple active AtomFlow Sandbox webhook settings exist (${activeDuplicates.map(item => item.id).join(", ")}); run setup mode to disable duplicates`,
    );
  }
  if (verifyOnly && !notificationHasExpectedConfiguration(canonical, webhookUrl)) {
    throw new Error("AtomFlow Sandbox webhook destination exists but its event/security settings are incorrect");
  }

  let resolved = canonical;
  if (!verifyOnly && !notificationHasExpectedConfiguration(canonical, webhookUrl)) {
    resolved = await resource.update(canonical.id, {
      description: SANDBOX_NOTIFICATION_DESCRIPTION,
      destination: webhookUrl,
      active: true,
      subscribedEvents: [...SANDBOX_WEBHOOK_EVENTS],
      includeSensitiveFields: false,
      trafficSource: "all",
    });
  }
  if (!verifyOnly) {
    for (const duplicate of activeDuplicates) {
      try {
        await resource.update(duplicate.id, { active: false });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`Failed to disable duplicate AtomFlow Sandbox webhook ${duplicate.id}: ${message}`);
      }
    }
  }
  return resolved;
};

const ensureLocalTestAccount = async () => {
  const connectionString = required("DATABASE_URL");
  validateLocalPostgresUrl(connectionString);
  const configuredEmail = process.env.TEST_EMAIL?.trim().toLowerCase();
  const configuredPassword = process.env.TEST_PASSWORD?.trim();
  if ((configuredEmail && !configuredPassword) || (!configuredEmail && configuredPassword)) {
    throw new Error("TEST_EMAIL and TEST_PASSWORD must be provided together");
  }
  const email = configuredEmail || `billing-sandbox-${randomBytes(8).toString("hex")}@example.com`;
  const password = configuredPassword || randomBytes(24).toString("base64url");
  const pool = new pg.Pool({ connectionString, max: 1 });
  try {
    const existing = (await pool.query(
      `SELECT id, password_hash AS "passwordHash" FROM users WHERE lower(email) = lower($1) LIMIT 1`,
      [email],
    )).rows[0] as { id: number; passwordHash: string | null } | undefined;
    if (existing) {
      if (!existing.passwordHash || !(await bcrypt.compare(password, existing.passwordHash))) {
        throw new Error("Configured Sandbox TEST_EMAIL already exists but TEST_PASSWORD does not match");
      }
    } else {
      const passwordHash = await bcrypt.hash(password, 12);
      await pool.query(
        `INSERT INTO users (email, nickname, avatar_url, password_hash)
         VALUES ($1, $2, NULL, $3)`,
        [email, "Paddle Sandbox", passwordHash],
      );
    }
    return { email, password };
  } finally {
    await pool.end();
  }
};

const writePrivateGeneratedFile = async (outputPath: string, body: string) => {
  try {
    const existing = await fs.readFile(outputPath, "utf8");
    if (!existing.startsWith(GENERATED_MARKER)) {
      throw new Error(`${outputPath} exists but was not generated by this script`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const temporaryPath = `${outputPath}.tmp`;
  await fs.writeFile(temporaryPath, body, { encoding: "utf8", mode: 0o600 });
  await fs.rename(temporaryPath, outputPath);
  await fs.chmod(outputPath, 0o600);
};

const main = async () => {
  dotenv.config();
  dotenv.config({ path: ".env.billing.sandbox" });
  dotenv.config({ path: ".env.billing.test-account" });
  dotenv.config({ path: ".env.paddle.sandbox", override: true });
  if (unknownArguments.length > 0) throw new Error(`Unknown argument: ${unknownArguments.join(", ")}`);
  if (localAccountOnly) {
    if (verifyOnly) throw new Error("--local-account-only cannot be combined with --verify-only");
    const testAccount = await ensureLocalTestAccount();
    await writePrivateGeneratedFile(TEST_ACCOUNT_OUTPUT_PATH, [
      `${GENERATED_MARKER} Local test account only.`,
      "# This file is ignored by git. Do not use this account against production.",
      `TEST_EMAIL=${JSON.stringify(testAccount.email)}`,
      `TEST_PASSWORD=${JSON.stringify(testAccount.password)}`,
      "",
    ].join("\n"));
    console.log(JSON.stringify({
      environment: "local",
      mode: "test-account",
      envFile: TEST_ACCOUNT_OUTPUT_PATH,
      next: "Use the generated credentials only with the loopback AtomFlow database.",
    }, null, 2));
    return;
  }
  const apiKey = required("PADDLE_API_KEY");
  if (!/^pdl_sdbx_apikey_/i.test(apiKey)) {
    throw new Error("setup-paddle-sandbox refuses non-Sandbox API keys");
  }
  const webhookUrl = validateSandboxWebhookUrl(required("PADDLE_WEBHOOK_URL"));
  const paddle = new Paddle(apiKey, { environment: Environment.sandbox });

  const products = await collect(paddle.products.list({ status: ["active"], perPage: 200 }));
  let product = oneOrNone(products.filter(item => (
    asRecord(item.customData).atomflow_catalog_key === SANDBOX_PRODUCT_KEY
  )), "Sandbox products");
  if (!product) {
    if (verifyOnly) throw new Error("AtomFlow Sandbox product is missing");
    product = await paddle.products.create({
      name: SANDBOX_PRODUCT_NAME,
      description: "AtomFlow 的画布、文章、Skills 与写作 Agent 订阅",
      taxCategory: "saas",
      customData: { atomflow_catalog_key: SANDBOX_PRODUCT_KEY },
    });
  }
  if (product.taxCategory !== "saas" || product.name !== SANDBOX_PRODUCT_NAME) {
    throw new Error("Existing AtomFlow Sandbox product does not match the approved name/tax category");
  }

  const existingPrices = await collect(paddle.prices.list({
    productId: [product.id],
    status: ["active"],
    recurring: true,
    perPage: 200,
  }));
  const prices = new Map<string, (typeof existingPrices)[number]>();
  for (const spec of SANDBOX_PLAN_SPECS) {
    let price = oneOrNone(existingPrices.filter(item => (
      asRecord(item.customData).atomflow_plan_code === spec.code
    )), `${spec.code} prices`);
    if (!price) {
      if (verifyOnly) throw new Error(`Sandbox price ${spec.code} is missing`);
      price = await paddle.prices.create({
        productId: product.id,
        name: spec.name,
        description: spec.description,
        unitPrice: { amount: spec.amount, currencyCode: spec.currencyCode },
        billingCycle: { interval: spec.interval, frequency: spec.frequency },
        trialPeriod: null,
        taxMode: "account_setting",
        quantity: { minimum: 1, maximum: 1 },
        customData: { atomflow_plan_code: spec.code },
      });
    }
    if (!priceMatchesSandboxPlan(price, spec)) {
      throw new Error(`Existing Sandbox price ${spec.code} does not match its approved amount, currency, cycle, or no-trial policy`);
    }
    prices.set(spec.code, price);
  }

  const tokens = await collect(paddle.clientTokens.list({ status: ["active"], perPage: 200 }));
  let clientToken = oneOrNone(tokens.filter(item => item.name === SANDBOX_CLIENT_TOKEN_NAME), "Sandbox client tokens");
  if (!clientToken) {
    if (verifyOnly) throw new Error("AtomFlow Sandbox client token is missing");
    clientToken = await paddle.clientTokens.create({
      name: SANDBOX_CLIENT_TOKEN_NAME,
      description: "Public Paddle.js token for local AtomFlow Sandbox checkout",
    });
  } else if (!clientToken.token) {
    clientToken = await paddle.clientTokens.get(clientToken.id);
  }
  if (!/^test_/i.test(clientToken.token)) throw new Error("Paddle returned a non-Sandbox client token");

  const notificationSettings = await paddle.notificationSettings.list({ perPage: 200 });
  const notification = await reconcileSandboxNotificationSetting({
    notificationSettings,
    webhookUrl,
    verifyOnly,
    resource: paddle.notificationSettings,
  });
  if (!notification.endpointSecretKey) throw new Error("Paddle did not return the Sandbox webhook secret");

  const monthlyPrice = prices.get("pro_monthly");
  const yearlyPrice = prices.get("pro_yearly");
  if (!monthlyPrice || !yearlyPrice) throw new Error("Sandbox price provisioning was incomplete");

  if (!verifyOnly) {
    const testAccount = await ensureLocalTestAccount();
    const body = renderSandboxBillingEnv({
      apiKey,
      webhookSecret: notification.endpointSecretKey,
      clientToken: clientToken.token,
      productId: product.id,
      monthlyPriceId: monthlyPrice.id,
      yearlyPriceId: yearlyPrice.id,
      webhookUrl,
      simulationIds: process.env.PADDLE_SANDBOX_SIMULATION_IDS?.trim(),
      testBaseUrl: process.env.BILLING_TEST_BASE_URL?.trim(),
      testEmail: testAccount.email,
      testPassword: testAccount.password,
    });
    await writePrivateGeneratedFile(OUTPUT_PATH, body);
  }

  console.log(JSON.stringify({
    environment: "sandbox",
    mode: verifyOnly ? "verify" : "setup",
    productId: product.id,
    monthlyPriceId: monthlyPrice.id,
    yearlyPriceId: yearlyPrice.id,
    clientTokenId: clientToken.id,
    notificationSettingId: notification.id,
    webhookUrl,
    envFile: verifyOnly ? null : OUTPUT_PATH,
    next: "Set the Paddle Sandbox default payment link, create webhook simulations, then run npm run billing:dev:sandbox and npm run billing:test:sandbox.",
  }, null, 2));
};

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  main().catch(error => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
