import { isIP } from "node:net";

export const SANDBOX_PRODUCT_KEY = "atomflow_magic_write_pro_v1";
export const SANDBOX_PRODUCT_NAME = "AtomFlow 魔法写作 Pro";
export const SANDBOX_CLIENT_TOKEN_NAME = "AtomFlow Sandbox Web";
export const SANDBOX_NOTIFICATION_DESCRIPTION = "AtomFlow Sandbox billing";

export const SANDBOX_WEBHOOK_EVENTS = [
  "subscription.created",
  "subscription.updated",
  "subscription.activated",
  "subscription.past_due",
  "subscription.paused",
  "subscription.resumed",
  "subscription.canceled",
  "transaction.completed",
  "transaction.payment_failed",
  "adjustment.updated",
] as const;

export type SandboxPlanSpec = {
  code: "pro_monthly" | "pro_yearly";
  name: string;
  description: string;
  amount: string;
  currencyCode: "CNY";
  interval: "month" | "year";
  frequency: number;
};

export const SANDBOX_PLAN_SPECS: readonly SandboxPlanSpec[] = [
  {
    code: "pro_monthly",
    name: "魔法写作 Pro 月付",
    description: "AtomFlow 魔法写作 Pro，按月自动续费",
    amount: "3900",
    currencyCode: "CNY",
    interval: "month",
    frequency: 1,
  },
  {
    code: "pro_yearly",
    name: "魔法写作 Pro 年付",
    description: "AtomFlow 魔法写作 Pro，按年自动续费",
    amount: "39900",
    currencyCode: "CNY",
    interval: "year",
    frequency: 1,
  },
] as const;

type PriceLike = {
  unitPrice?: { amount?: unknown; currencyCode?: unknown } | null;
  billingCycle?: { interval?: unknown; frequency?: unknown } | null;
  trialPeriod?: unknown;
};

export const priceMatchesSandboxPlan = (price: PriceLike, spec: SandboxPlanSpec) => (
  price.unitPrice?.amount === spec.amount
  && price.unitPrice?.currencyCode === spec.currencyCode
  && price.billingCycle?.interval === spec.interval
  && price.billingCycle?.frequency === spec.frequency
  && price.trialPeriod == null
);

export const validateSandboxWebhookUrl = (raw: string) => {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new Error("PADDLE_WEBHOOK_URL must be a valid public HTTPS URL");
  }
  const hostname = url.hostname.toLowerCase();
  if (
    url.protocol !== "https:"
    || url.username
    || url.password
    || url.search
    || url.hash
    || url.pathname !== "/api/billing/webhooks/paddle"
    || isIP(hostname) !== 0
    || hostname === "localhost"
    || hostname.endsWith(".localhost")
    || !hostname.includes(".")
  ) {
    throw new Error("PADDLE_WEBHOOK_URL must be a public HTTPS domain ending in /api/billing/webhooks/paddle");
  }
  return url.toString();
};

const normalizeUrlHostname = (hostname: string) => hostname.toLowerCase().replace(/^\[|\]$/g, "");
const isLoopbackHostname = (hostname: string) => ["localhost", "127.0.0.1", "::1"].includes(normalizeUrlHostname(hostname));

export const validateLocalPostgresUrl = (raw: string) => {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new Error("DATABASE_URL must be a loopback PostgreSQL URL for Sandbox tests");
  }
  if (
    (url.protocol !== "postgres:" && url.protocol !== "postgresql:")
    || !isLoopbackHostname(url.hostname)
    || url.search
    || url.hash
    || !url.pathname
    || url.pathname === "/"
  ) {
    throw new Error("Sandbox tests require a loopback PostgreSQL URL without connection-option overrides");
  }
  return raw;
};

export const validateLocalBillingTestBaseUrl = (raw: string) => {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new Error("BILLING_TEST_BASE_URL must be the local AtomFlow origin");
  }
  if (
    url.protocol !== "http:"
    || !isLoopbackHostname(url.hostname)
    || url.port !== "1000"
    || url.username
    || url.password
    || url.pathname !== "/"
    || url.search
    || url.hash
  ) {
    throw new Error("BILLING_TEST_BASE_URL must be the loopback AtomFlow origin on port 1000");
  }
  return url.origin;
};

const quoteEnv = (value: string) => JSON.stringify(value);

export type SandboxBillingEnv = {
  apiKey: string;
  webhookSecret: string;
  clientToken: string;
  productId: string;
  monthlyPriceId: string;
  yearlyPriceId: string;
  webhookUrl: string;
  simulationIds?: string;
  testBaseUrl?: string;
  testEmail?: string;
  testPassword?: string;
};

export const renderSandboxBillingEnv = (values: SandboxBillingEnv) => [
  "# Generated by scripts/setup-paddle-sandbox.ts. Local Sandbox use only.",
  "# This file is ignored by git and must never be copied to Railway production.",
  "BILLING_ENABLED=true",
  "PADDLE_ENVIRONMENT=sandbox",
  "VITE_PADDLE_ENVIRONMENT=sandbox",
  `PADDLE_API_KEY=${quoteEnv(values.apiKey)}`,
  `PADDLE_WEBHOOK_SECRET=${quoteEnv(values.webhookSecret)}`,
  `VITE_PADDLE_CLIENT_TOKEN=${quoteEnv(values.clientToken)}`,
  `PADDLE_MAGIC_WRITE_PRODUCT_ID=${quoteEnv(values.productId)}`,
  `PADDLE_MAGIC_WRITE_MONTHLY_PRICE_ID=${quoteEnv(values.monthlyPriceId)}`,
  `PADDLE_MAGIC_WRITE_YEARLY_PRICE_ID=${quoteEnv(values.yearlyPriceId)}`,
  "PADDLE_MAGIC_WRITE_LEGACY_PRICE_IDS=\"\"",
  `PADDLE_WEBHOOK_URL=${quoteEnv(values.webhookUrl)}`,
  "RUN_REAL_BILLING_TESTS=false",
  `BILLING_TEST_BASE_URL=${quoteEnv(validateLocalBillingTestBaseUrl(values.testBaseUrl || "http://localhost:1000"))}`,
  `PADDLE_SANDBOX_SIMULATION_IDS=${quoteEnv(values.simulationIds || "")}`,
  `TEST_EMAIL=${quoteEnv(values.testEmail || "")}`,
  `TEST_PASSWORD=${quoteEnv(values.testPassword || "")}`,
  "",
].join("\n");
